# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- setup --------------------------------------------------------------------

import datetime
import os
import xml.etree.ElementTree as ET

now = datetime.datetime.now()

#Current year
year = now.year

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'GeoServer Enterprise'
copyright = u'{}, GeoCat BV'.format(year)
author = 'GeoCat BV'

# The full version, including alpha/beta/rc tags
pompath = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), "geoserver", "src", "pom.xml")
pomtree = ET.parse(pompath)
release = pomtree.getroot().find("{http://maven.apache.org/POM/4.0.0}version").text
snapshot = release.find('SNAPSHOT') != -1

# The short X.Y version
version = ".".join(release.split(".")[:2])

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
  'sphinx.ext.ifconfig',
  'sphinx.ext.extlinks',
  'sphinx.ext.todo'
  # 'recommonmark'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    '.rst': 'restructuredtext'
    # '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Extension External Links ------------------------------------------------
extlinks = { 
    'wiki': ('https://github.com/geoserver/geoserver/wiki/%s',''),
    'website': ('http://geoserver.org/%s',''),
    'user': ('https://www.geocat.net/docs/geoserver-enterprise/v'+version+'/%s',''),
    'developer': ('http://docs.geoserver.org/latest/en/developer/%s',''),
    'docguide': ('http://docs.geoserver.org/latest/en/docguide/%s',''),
    'geos': ('https://osgeo-org.atlassian.net/browse/GEOS-%s','GEOS-'),
    'geot': ('https://osgeo-org.atlassian.net/browse/GEOT-%s','GEOT-'),
    'geotools': ('https://docs.geotools.org/stable/userguide/%s',''),
    'api': ('http://docs.geoserver.org/latest/en/api/#1.0.0/%s',''),
    'download_release': ('http://sourceforge.net/projects/geoserver/files/GeoServer/'+release+'/geoserver-'+release+'-%s.zip',None),
    'download_extension': ('http://sourceforge.net/projects/geoserver/files/GeoServer/'+release+'/extensions/geoserver-'+release+'-%s-plugin.zip',None),
    'download_community': ('https://github.com/geoserver/geoserver/tree/'+version+'/src/community/%s',None)
}

# Common substitutions

rst_epilog = "\n" \
 ".. |install_directory_winXP| replace:: :file:`C:\\\\Program Files\\\\GeoServer "+release+"`\n" \
 ".. |install_directory_win| replace:: :file:`C:\\\\Program Files (x86)\\\\GeoServer "+release+"`\n" \
 ".. |install_directory_linux| replace:: :file:`/var/lib/tomcat8/webapps/geoserver`\n" \
 ".. |install_directory_mac| replace:: :file:`/Applications`\n" \
 ".. |data_directory_winXP| replace:: :file:`C:\\\\ProgramData\\\\GeoServer\\\\Data`\n" \
 ".. |data_directory_win| replace:: :file:`C:\\\\ProgramData\\\\GeoServer\\\\\Data`\n" \
 ".. |data_directory_linux| replace:: :file:`/var/lib/tomcat8/webapps/geoserver/data`\n" \
 ".. |data_directory_mac| replace:: :file:`/Application Support/GeoServer/Data`"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'geocat_rtd'

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['../../themes']

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'logo_only': True,                  # product logo contains name already
    'display_version': False,           # no version number
    'prev_next_buttons_location': None, # table of contents navigation
    'style_external_links': False,      # user guide links common
    'includehidden': False,
    'titles_only': True,
    'collapse_navigation': True,
    'show_sphinx': 'Green',
    'is_prerelease': False
}

html_context = {'theme_is_prerelease': snapshot}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'geoserver.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'favicon.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_show_sourcelink = False

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'GeoServerEnterprisedoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'GeoServerEnterprise.tex', 'GeoServer Enterprise Documentation',
     'GeoCat BV', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'geoserverenterprise', 'GeoServer Enterprise Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'GeoServerEnterprise', 'GeoServer Enterprise Documentation',
     author, 'GeoServerEnterprise', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']
